apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ashu-pod-access
  namespace: ashu-restricted
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
