apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashulb2
  name: ashulb2
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: ashu-deploy
  type: LoadBalancer

