apiVersion: v1
kind: Service
metadata:
  namespace: ashu-project 
  creationTimestamp: null
  labels:
    app: ashuwebsvc
  name: ashuwebsvc
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # pod finder using pod label 
    x: helloashu # label of pod 
  type: NodePort
status:
  loadBalancer: {}
